# Day 1: Review of Basic Python and Jupyter Notebook for Data Science


[Python Cheat Sheet](https://datacamp-community-prod.s3.amazonaws.com/e30fbcd9-f595-4a9f-803d-05ca5bf84612)

[Markdown cheat sheet](https://www.markdownguide.org/cheat-sheet/)

Special Notes:
1. Variable types are Numeric, String, Boolean, Special literal (x=none), literal collection (collection like JSON)
2. list starts from 0
3. When you set range in a list, the last one doesn't count


In [23]:
#List
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50


house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]
print(house)



[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]


['kitchen', 18.0]

In [32]:
#Subsetting List: first bracket is choosing which list to choose inside variable house, second is choosing within
house[4][:]

['bathroom', 9.5]

In [39]:
#Built in Functions
list = [1.4231,2.421,3.3245,4,5]

max(list) #max function

5

In [45]:
round(list[0], 2) #round function

1.42

In [41]:
round(list[0]) #round up to no decimal point

1

In [46]:
len(list) #getting the length

5

sorted() takes iterable $key$ and $reverse$ as their parameter. If reverse is True, it shows in descending order

In [51]:
# Sorting List from highest to lowest 
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first+second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse = True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


Methods are functions that belong to the objects
Methods for object types:

- str : capitalize(), replace()
- float : bit_length(), conjugate()
- list : index(), count()  ex) variable.index("something") shows index(position) of something in the list. variable.count("something") counts the number of something in the list

In [53]:
#list methods
PoS = ["Sunny", 1, "Koby", 2, "Josh", 3]
#indexing position (search): Sunny is in index 0
PoS.index("Sunny")

0

In [56]:
#counting: Sunny appears once in PoS
PoS.count("Sunny")

1

In [59]:
#reversing: reversed the list
PoS.reverse()
print(PoS)

[3, 'Josh', 2, 'Koby', 1, 'Sunny']


In [62]:
#string methods
myname = 'sunny'
#capitalzing the value in string. List is not possible
myname.capitalize()

'Sunny'

In [65]:
#replacing certain letter in string
myname.replace("y", "i")

'sunni'

In [67]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place
print(place.count("o"))

poolhouse
POOLHOUSE
3


## Packages

Packages are directory of python scripts. Each script is a module, where it specifies functions, methods, and types that will be used to solve a problem. NumPy is widly used for arrays, Matplotlib for data visualization, and scikit-learn for machine learning (tensorflow)


$pip$
pip stands for package maintenance system for python.  for installation:
https://pip.readthedocs.io/en/stable/installing/

Once pip is installed, you can use 

pip3 install whatever

to download whatever package you need



In [68]:
#ways to import library
import numpy as np
np.array([1,2,3])

from numpy import array
array([1,2,3]) #but avoid using this because if the line of code is very long, it would be hard to track which library array is imported from.

array([1, 2, 3])

## Numpy
NumPy array could also be helpful in the situation where you have to do calculation on each elements within the array. In another words, element level calculation is possible. But numpy needs to have same variable type

In [70]:
#numpy example
import numpy as np

height_in = [52, 42, 43, 15]
weight_lb = [160, 145, 170, 124]
# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg/np_height_m**2

# Print out bmi
print(bmi)


[ 41.60171634  57.79195345  64.64128234 387.46914116]


But subsetting works exactly the same as list for NumPy arrays.

In NumPy, you can make a matrix using n-D array (1d,2d)
When you look at the type() for arrays, it prints "numpy.ndarray". this means n-dimentional array in numpy package.
So creating two array within an array would make it 2d array, each array is a row.
Again, it can only contain one single type

Note when subsetting, index starts from 0

- np_2d[0][1] : first(0 is the first index) row, second(1 is the second index) column
- np_2d[0,1] : same result
- Therefore: [row, column]

mean, median, corrcoef (to see if two variables are correlated), and std (standard deviation), sum, sort is included in numpy.


In [77]:
height_in = [52, 42, 43, 15]
np.mean(height_in)
#test out median, corrcoef, std, sum, and sort

38.0